# Generated by Django 3.1.3 on 2021-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('sub', models.CharField(choices=[('Male', 'Male'), ('female', 'female')], max_length=90)),
                ('add', models.CharField(max_length=90)),
            ],
        ),
    ]
